feat: new deployment suitable for service discovery in cluster

diff --git a/deploy-ecs b/deploy-ecs
--- a/deploy-ecs
+++ b/deploy-ecs
@@ -1,39 +1,48 @@
-#!/bin/sh
+#!/bin/bash
 
+source mycs-functions
+
+# Default
 VERSION="0.1.0"
 VERBOSE=false
 AWS_CLI=$(which aws)
 AWS_ECS="$AWS_CLI --output json ecs"
 AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-eu-west-1}
 AWS_ASSUME_ROLE=true
+COUNT=1
 
-function usage() {
+usage () {
 cat <<EOM
--- ecs-cf-deploy --
+-- deploy --
 
-Simple script to force a deployement of an ECS service based on a clouformation stack.
+Deploy an ecs-service in the ecs-cluster
 
 Required arguments:
+    -p  | --repo                  Name of the repo
+    -b  | --branch                Branch that needs to be deployed
+    -t  | --task-path             Path to the file describing the task definition
     -c  | --cluster-name          Name of cloudformation stack containing the ecs cluster to deploy
-    -s  | --service-name          Name of cloudformation stack containing the service to deploy
     -a  | --account               ID of the account to assume the role
     -ar | --assume-role-name      Name of the role to assume
+    -sn | --service-name          Name of the service stack
 
 Optional arguments:
     -k  | --aws-access-key        AWS Access Key ID. May also be set as environment variable AWS_ACCESS_KEY_ID
     -s  | --aws-secret-key        AWS Secret Access Key. May also be set as environment variable AWS_SECRET_ACCESS_KEY
     -r  | --region                AWS Region Name. May also be set as environment variable AWS_DEFAULT_REGION or use the default eu-west-1
     -v  | --verbose               Display debugging information (basically each command)
+    -co | --count                 Amount of tasks to create for that service (default to 1)
 
 Requirements:
+    git:  Git CLI
     aws:  AWS Command Line Interface
     jq:   Command-line JSON processor
 
 Example:
-    ecs-cf-deploy -s example-api -c example-cluster -a 1234465780 -ar assumeRoleName -r us-west-1
+    deploy-ecs -sn example-api -c example-cluster -a 1234465780 -ar assumeRoleName -r us-west-1 -p example-api -b test
 
 Author:
-  Nicolas Ritouet <nicolas@mycs.com>
+  Julien Abega <julien@mycs.com>
 
 License:
   MIT (check LICENSE.md)
@@ -42,79 +51,9 @@ EOM
 }
 
 
-# Check requirements
-function require() {
-    command -v "$1" > /dev/null 2>&1 || {
-        echo "Some of the required software is not installed:"
-        echo "    please install $1" >&2;
-        exit 4;
-    }
-}
-
-function assumeRole() {
-
-    temp_role=$($AWS_CLI sts assume-role --role-arn "arn:aws:iam::${ACCOUNT_ID}:role/${CROSS_ACCOUNT_ROLE}" --role-session-name "$(date +"%s")")
-    
-    export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq .Credentials.AccessKeyId | xargs)
-    export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq .Credentials.SecretAccessKey | xargs)
-    export AWS_SESSION_TOKEN=$(echo $temp_role | jq .Credentials.SessionToken | xargs)
-}
-
-function assumeRoleClean() {
-    unset AWS_ACCESS_KEY_ID
-    unset AWS_SECRET_ACCESS_KEY
-    unset AWS_SESSION_TOKEN
-}
-
-function getClusterName() {
-    export ECS_CLUSTER_NAME=$($AWS_CLI cloudformation describe-stacks \
-              --stack-name ${ECS_CLUSTER_STACK} \
-              --query 'Stacks[0].Outputs[?OutputKey==`Cluster`].OutputValue' \
-              --output text --region ${AWS_DEFAULT_REGION}
-              )
-  if [ -z $ECS_CLUSTER_NAME ]; then
-    echo "Could not find the service under the '$ECS_CLUSTER_STACK' stack"
-    exit 9
-  fi
-}
-
-function getServiceName() {
-    export ECS_SERVICE_NAME=$($AWS_CLI cloudformation describe-stacks \
-              --stack-name ${ECS_SERVICE_STACK} \
-              --query 'Stacks[0].Outputs[?OutputKey==`Service`].OutputValue' \
-              --output text --region ${AWS_DEFAULT_REGION}
-              )
-    if [ $ECS_SERVICE_NAME == $ECS_CLUSTER_NAME ]; then
-      echo "Long ARN bug found: using ServiceArn output to get Service name";
-      temp_servicename=$($AWS_CLI cloudformation describe-stacks \
-              --stack-name ${ECS_SERVICE_STACK} \
-              --query 'Stacks[0].Outputs[?OutputKey==`Service`].OutputValue' \
-              --output text --region ${AWS_DEFAULT_REGION}
-              )
-      echo $ECS_SERVICE_STACK
-      echo $temp_servicename
-      echo $ECS_SERVICE_NAME
-      export ECS_SERVICE_NAME=${temp_servicename##*/}
-    fi
-  if [ -z $ECS_SERVICE_NAME ]; then
-    echo "Could not find the service under the '$ECS_SERVICE_STACK' stack"
-    exit 10
-  fi
-}
-
-
-function updateService() {
-  if [ $VERBOSE == true ]; then
-    echo "Deploying on cluster '$ECS_CLUSTER_NAME' service '$ECS_SERVICE_NAME'";
-  fi
-    $AWS_ECS update-service --cluster $ECS_CLUSTER_NAME --service $ECS_SERVICE_NAME --force-new-deployment
-}
-
-
-
 
 # Check that all required variables/combinations are set
-function assertRequiredArgumentsSet() {
+assertRequiredArgumentsSet () {
 
     # AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_DEFAULT_REGION and AWS_PROFILE can be set as environment variables
     if [ -z ${AWS_ACCESS_KEY_ID+x} ]; then unset AWS_ACCESS_KEY_ID; fi
@@ -130,13 +69,13 @@ function assertRequiredArgumentsSet() {
               AWS_ECS="$AWS_ECS --profile $AWS_PROFILE"
     fi
 
-    if [ -z "${ECS_SERVICE_STACK:-}" ]; then
-        echo "SERVICE is required. You can pass the value using -s or --service-name"
-        exit 5
-    fi
-    if [ ! -z "${ECS_SERVICE_STACK:-}" ] && [ -z "${ECS_CLUSTER_STACK:-}" ]; then
+    if [ -z "${ECS_CLUSTER_STACK:-}" ]; then
         echo "CLUSTER is required. You can pass the value using -c or --cluster"
         exit 6
+    fi
+    if [ -z "${ECS_SERVICE_STACK:-}" ]; then
+        echo "SERVICE is required. You can pass the value using -sn or --service-name"
+        exit 5
     fi
     if [ -z "${ACCOUNT_ID:-}" ]; then
         echo "ACCOUNT is required. You can pass the value using -a or --account"
@@ -147,6 +86,36 @@ function assertRequiredArgumentsSet() {
         exit 8
     fi
 
+    if [ -z "${BRANCH:-}" ]; then
+        echo "BRANCH is required. You can pass the value using -b or --branch"
+        exit 8
+    fi
+
+    if [ -z "${REPONAME:-}" ]; then
+        echo "REPONAME is required. You can pass the value using -p or --repo"
+        exit 8
+    fi
+}
+
+deploy () {
+  echo "Deployment of service in ecs cluster ..."
+
+  setCommitMsg
+  setTaskDefinition
+
+  if echo $BRANCH | grep -E '^(production|staging|master)$'
+  then
+    echo "Service $ECS_SERVICE_STACK will be deployed because $BRANCH is a main branch"
+    createService
+    echo "Service $SERVICE_ARN deployment was initialized properly"
+  elif echo $COMMIT_MSG | grep -E '\[deploy\]'
+  then
+    echo "Service $ECS_SERVICE_STACK will be deployed because [deploy] command was matched"
+    createService
+    echo "Service $SERVICE_ARN deployment was initialized properly"
+  else
+    echo "Service $ECS_SERVICE_STACK won't be deployed"
+  fi
 }
 
 ######################################################
@@ -154,7 +123,6 @@ function assertRequiredArgumentsSet() {
 ######################################################
 if [ -z "$TEST_ENV" ]; then
   set -o errexit
-  set -o pipefail
   set -u
   set -e
   # If no args are provided, display usage information
@@ -164,6 +132,10 @@ if [ -z "$TEST_ENV" ]; then
   require aws
   # Check for jq, Command-line JSON processor
   require jq
+  # Check for git
+  require git
+
+  # Default values
 
   # Loop through arguments, two at a time for key and value
   while [[ $# -gt 0 ]]
@@ -171,12 +143,24 @@ if [ -z "$TEST_ENV" ]; then
       key="$1"
 
       case $key in
+          -b|--branch)
+              BRANCH="$2"
+              shift
+              ;;
+          -p|--repo)
+              REPONAME="$2"
+              shift
+              ;;
+          -sn|--service-name)
+              ECS_SERVICE_STACK="$2"
+              shift
+              ;;
+          -co|--count)
+              COUNT="$2"
+              shift
+              ;;
           -c|--cluster-name)
               ECS_CLUSTER_STACK="$2"
-              shift # past argument
-              ;;
-          -s|--service-name)
-              ECS_SERVICE_STACK="$2"
               shift # past argument
               ;;
           -ar|--assume-role-name)
@@ -227,9 +211,8 @@ if [ -z "$TEST_ENV" ]; then
   fi
 
   getClusterName
-  getServiceName
-  updateService
 
+  deploy
 
   if [[ "$AWS_ASSUME_ROLE" != false ]]; then
       assumeRoleClean
@@ -237,6 +220,3 @@ if [ -z "$TEST_ENV" ]; then
 
   exit 0
 fi
-#############################
-# End application run logic #
-#############################
