Add tests

diff --git a/ecs-cf-deploy b/ecs-cf-deploy
--- a/ecs-cf-deploy
+++ b/ecs-cf-deploy
@@ -7,7 +7,6 @@ AWS_ECS="$AWS_CLI --output json ecs"
 AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-"eu-west-1"}
 AWS_ASSUME_ROLE=true
 
-
 function usage() {
 cat <<EOM
 -- ecs-cf-deploy --
@@ -121,7 +120,11 @@ function assertRequiredArgumentsSet() {
     fi
     if [ -z "${ACCOUNT_ID:-}" ]; then
         echo "ACCOUNT is required. You can pass the value using -a or --account"
-        exit 6
+        exit 7
+    fi
+    if [ -z "${CROSS_ACCOUNT_ROLE:-}" ]; then
+        echo "ROLE_NAME is required. You can pass the value using -ar or --assume-role-name"
+        exit 8
     fi
 
 }
@@ -129,91 +132,91 @@ function assertRequiredArgumentsSet() {
 ######################################################
 # When not being tested, run application as expected #
 ######################################################
-set -o errexit
-set -o pipefail
-set -u
-set -e
+if [ -z "$TEST_ENV" ]; then
+  set -o errexit
+  set -o pipefail
+  set -u
+  set -e
+  # If no args are provided, display usage information
+  if [ $# == 0 ]; then usage; fi
 
-# If no args are provided, display usage information
-if [ $# == 0 ]; then usage; fi
+  # Check for AWS, AWS Command Line Interface
+  require aws
+  # Check for jq, Command-line JSON processor
+  require jq
 
-# Check for AWS, AWS Command Line Interface
-require aws
-# Check for jq, Command-line JSON processor
-require jq
+  # Loop through arguments, two at a time for key and value
+  while [[ $# -gt 0 ]]
+  do
+      key="$1"
 
-# Loop through arguments, two at a time for key and value
-while [[ $# -gt 0 ]]
-do
-    key="$1"
+      case $key in
+          -c|--cluster-name)
+              ECS_CLUSTER_STACK="$2"
+              shift # past argument
+              ;;
+          -s|--service-name)
+              ECS_SERVICE_STACK="$2"
+              shift # past argument
+              ;;
+          -ar|--assume-role-name)
+              CROSS_ACCOUNT_ROLE="$2"
+              shift # past argument
+              ;;
+          -a|--account)
+              ACCOUNT_ID="$2"
+              shift # past argument
+              ;;
+          -k|--aws-access-key)
+              AWS_ACCESS_KEY_ID="$2"
+              shift # past argument
+              ;;
+          -s|--aws-secret-key)
+              AWS_SECRET_ACCESS_KEY="$2"
+              shift # past argument
+              ;;
+          -r|--region)
+              AWS_DEFAULT_REGION="$2"
+              shift # past argument
+              ;;
+          -v|--verbose)
+              VERBOSE=true
+              ;;
+          --version)
+              echo ${VERSION}
+              exit 0
+              ;;
+          *)
+              echo "Found nothing, will display usage and exit"
+              usage
+              exit 2
+          ;;
+      esac
+      shift # past argument or value
+  done
 
-    case $key in
-        -c|--cluster-name)
-            ECS_CLUSTER_STACK="$2"
-            shift # past argument
-            ;;
-        -s|--service-name)
-            ECS_SERVICE_STACK="$2"
-            shift # past argument
-            ;;
-        -ar|--assume-role-name)
-            CROSS_ACCOUNT_ROLE="$2"
-            shift # past argument
-            ;;
-        -a|--account)
-            ACCOUNT_ID="$2"
-            shift # past argument
-            ;;
-        -k|--aws-access-key)
-            AWS_ACCESS_KEY_ID="$2"
-            shift # past argument
-            ;;
-        -s|--aws-secret-key)
-            AWS_SECRET_ACCESS_KEY="$2"
-            shift # past argument
-            ;;
-        -r|--region)
-            AWS_DEFAULT_REGION="$2"
-            shift # past argument
-            ;;
-        -v|--verbose)
-            VERBOSE=true
-            ;;
-        --version)
-            echo ${VERSION}
-            exit 0
-            ;;
-        *)
-            echo "Found nothing, will display usage and exit"
-            usage
-            exit 2
-        ;;
-    esac
-    shift # past argument or value
-done
+  if [ $VERBOSE == true ]; then
+      set -x
+  fi
 
-if [ $VERBOSE == true ]; then
-    set -x
+  # Check that required arguments are provided
+  assertRequiredArgumentsSet
+
+  if [[ "$AWS_ASSUME_ROLE" != false ]]; then
+      assumeRole
+  fi
+
+  getClusterName
+  getServiceName
+  updateService
+
+
+  if [[ "$AWS_ASSUME_ROLE" != false ]]; then
+      assumeRoleClean
+  fi
+
+  exit 0
 fi
-
-# Check that required arguments are provided
-assertRequiredArgumentsSet
-
-if [[ "$AWS_ASSUME_ROLE" != false ]]; then
-    assumeRole
-fi
-
-getClusterName
-getServiceName
-updateService
-
-
-if [[ "$AWS_ASSUME_ROLE" != false ]]; then
-    assumeRoleClean
-fi
-
-exit 0
-
 #############################
 # End application run logic #
 #############################
