Back to alpine

diff --git a/ecs-cf-deploy b/ecs-cf-deploy
--- a/ecs-cf-deploy
+++ b/ecs-cf-deploy
@@ -54,7 +54,7 @@ function require() {
 function assumeRole() {
 
     temp_role=$($AWS_CLI sts assume-role --role-arn "arn:aws:iam::${ACCOUNT_ID}:role/${CROSS_ACCOUNT_ROLE}" --role-session-name "$(date +"%s")")
-
+    
     export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq .Credentials.AccessKeyId | xargs)
     export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq .Credentials.SecretAccessKey | xargs)
     export AWS_SESSION_TOKEN=$(echo $temp_role | jq .Credentials.SessionToken | xargs)
@@ -72,6 +72,10 @@ function getClusterName() {
               --query 'Stacks[0].Outputs[?OutputKey==`Cluster`].OutputValue' \
               --output text --region ${AWS_DEFAULT_REGION}
               )
+  if [ -z $ECS_CLUSTER_NAME ]; then
+    echo "Could not find the service under the '$ECS_CLUSTER_STACK' stack"
+    exit 9
+  fi
 }
 
 function getServiceName() {
@@ -80,6 +84,10 @@ function getServiceName() {
               --query 'Stacks[0].Outputs[?OutputKey==`Service`].OutputValue' \
               --output text --region ${AWS_DEFAULT_REGION}
               )
+  if [ -z $ECS_SERVICE_NAME ]; then
+    echo "Could not find the service under the '$ECS_SERVICE_STACK' stack"
+    exit 10
+  fi
 }
 
 
